# Use root/example as user/password credentials
version: '3.9'

services:
  nagios:
    build:
      context: .
    # depends_on:
    #   - db
    hostname: Nagios-SVR
    # networks:
    #   nagios_network:
    #     ipv4_address: 10.10.99.69
    environment:
      NAGIOS_PASSWORD: ${NAGIOS_PASSWORD}
      NAGIOS_ADMIN: ${NAGIOS_ADMIN}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "80:80"
      # - "22:22"
    # volumes:
    #   - nagios-data:/vol/web/static

  # db:
  #   build:
  #     context: ./mysql
  #   # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
  #   # (this is just an example, not intended to be a production configuration)
  #   hostname: db
  #   networks:
  #     - nagios_network
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

networks:
  nagios_network:
    ipam:
      driver: bridge
      config:
        - gateway: 10.10.99.2
        - subnet: 10.10.99.0/24

# volumes:
#   nagios-data: